name: hms_core
description: The Himalaya HMS Core Classes.
publish_to: none
version: 0.0.1

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: '>=3.10.4'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  go_router: ^8.0.5
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true